---
title: "US_Airline_Network_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### load packages
```{r load packages}
library("dplyr")
library("ggplot2")
```

### Load data
```{r}
load("airline16.Rdata")
load("airline1516.Rdata")
load("airline_sample.Rdata")
```

### Calculate daily volume of airports as an attribute of nodes
```{r}
airport_out = airline1516 %>% select(ORIGIN,FL_DATE) %>% group_by(ORIGIN,FL_DATE) %>% summarise(frequency = n()) %>% rename(airport = ORIGIN) %>% group_by(airport) %>% summarize(volume = mean(frequency))
airport_in = airline1516 %>% select(DEST,FL_DATE) %>% group_by(DEST,FL_DATE) %>% summarise(frequency = n()) %>% rename(airport = DEST) %>% group_by(airport) %>% summarise(volume = mean(frequency))
airport_volume = bind_rows(airport_in,airport_out) 
airport_volume = airport_volume%>% group_by(airport) %>% summarize(volume_in_out = sum(volume))
```

### Identify city of airports as an attribute of nodes
```{r}
airport_o_city = airline1516 %>% select(ORIGIN,ORIGIN_CITY_NAME) %>% distinct(ORIGIN,ORIGIN_CITY_NAME) %>% rename(airport = ORIGIN,city_name = ORIGIN_CITY_NAME)
airport_d_city = airline1516 %>% select(DEST,DEST_CITY_NAME) %>% distinct(DEST,DEST_CITY_NAME) %>% rename(airport = DEST,city_name = DEST_CITY_NAME)
airport_city = bind_rows(airport_o_city,airport_d_city)
airport_city = airport_city %>% distinct(airport,city_name) %>% arrange(airport)
```

### Identify state of airports as an attribute of nodes
```{r}
airport_o_state = airline1516 %>% select(ORIGIN,ORIGIN_STATE_NM) %>% distinct(ORIGIN,ORIGIN_STATE_NM) %>% rename(airport = ORIGIN,state_name = ORIGIN_STATE_NM)
airport_d_state = airline1516 %>% select(DEST,DEST_STATE_NM) %>% distinct(DEST,DEST_STATE_NM) %>% rename(airport = DEST,state_name = DEST_STATE_NM)
airport_state = bind_rows(airport_o_state,airport_d_state)
airport_state = airport_state %>% distinct(airport,state_name) %>% arrange(airport)
```

### Airport Delay Rate
```{r}
Dep_Delay_Rate = airline1516 %>% mutate(have_depdelay =ifelse(DEP_DELAY_NEW>0,1,0) ) %>% select(ORIGIN,have_depdelay)
Dep_Delay_Rate = Dep_Delay_Rate[complete.cases(Dep_Delay_Rate),]
Dep_Delay_Rate = Dep_Delay_Rate %>% rename(airport = ORIGIN) %>% arrange(airport) %>% group_by(airport) %>% summarize(frequency = sum(have_depdelay)/n())
```

### Airport Delay Average time histogram
```{r}
Dep_top10 = airline1516 %>% select(ORIGIN, DEP_DELAY_NEW) %>% filter(DEP_DELAY_NEW>10) %>% rename(airport = ORIGIN) %>% group_by(airport) %>% summarise(avg_delay_time = mean(DEP_DELAY_NEW)) %>% top_n(10,avg_delay_time)
Delay_top10_airport = Dep_top10[1]
Delay_top10_airport_hist = airline1516 %>% select(ORIGIN,DEP_DELAY_NEW) %>% filter(ORIGIN %in% Delay_top10_airport$airport, DEP_DELAY_NEW>0)
ggplot(Delay_top10_airport_hist,aes(x = ORIGIN, y = DEP_DELAY_NEW))+
  geom_boxplot()
```

### Airport Delay Average time(Regard delay under 10 minutes as on time)
```{r}
Dep_Delay_Time = airline1516 %>% select(ORIGIN, DEP_DELAY_NEW) %>% filter(DEP_DELAY_NEW>10) %>% rename(airport = ORIGIN) %>% group_by(airport) %>% summarise(avg_delay_time = mean(DEP_DELAY_NEW))
```

